version: "3.7"

services:
    logstash:
        image: docker.elastic.co/logstash/logstash:7.17.0
        environment:
          # Так как сейчас вы хотите запустить logstash без Elasticsearch, необходимо отключить встроенный мониторинг, отправляющий данные в ES
          XPACK_MONITORING_ENABLED: "false"
          ES_HOST: "elasticsearch:9200"
        ports:
          - "5044:5044/udp"
        volumes:
          # Монтируем файл с конфигурацией logstash
          - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
        # Запускаем с указанием конфигурационного файла
        command: logstash -f /usr/share/logstash/config/logstash.conf

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        environment:
        # Указываем ES запуститься в одном экземпляре
          discovery.type: single-node
        ports:
          - 9200:9200
        volumes:
          - /tmp/esdata:/tmp/elasticsearch/data
    # Обратите внимание: не стоит использовать для ELK тот же ES, который задействован для полнотекстового поиска в вашем сервисе

    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.2
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch
