version: "3.7"

services:
  fast_event_api:
    restart: unless-stopped
    build:
      context: fast_event_api
      dockerfile: Dockerfile
    container_name: fast_event_api
    env_file:
      - fa.env
    volumes:
      - ./fast_event_api:/fast_event_api:ro
    networks:
      - movies_network
    ports:
      - "8000:8000"
    command: ["python", "main.py"]
    depends_on:
      - kafka
      - zookeeper-kafka
      - zookeeper-clickhouse

  zookeeper-kafka:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - movies_network
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-kafka:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - movies_network

  zookeeper-clickhouse:
    image: zookeeper:3.5
    container_name: zookeeper-clickhouse
    hostname: zookeeper
    networks:
      - movies_network

  clickhouse-node1:
    image: yandex/clickhouse-server
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./fast_event_api/clickhouse/node1:/etc/clickhouse-server
      - ./fast_event_api/clickhouse/scripts:/tmp
    depends_on:
      - zookeeper-clickhouse
    networks:
      - movies_network

  clickhouse-node2:
    image: yandex/clickhouse-server
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./fast_event_api/clickhouse/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper-clickhouse
    networks:
      - movies_network

  clickhouse-node3:
    image: yandex/clickhouse-server
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./fast_event_api/clickhouse/node3:/etc/clickhouse-server
      - ./fast_event_api/clickhouse/scripts:/tmp
    depends_on:
      - zookeeper-clickhouse
    networks:
      - movies_network

  clickhouse-node4:
    image: yandex/clickhouse-server
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./fast_event_api/clickhouse/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper-clickhouse
    networks:
      - movies_network


volumes:
  static_volume:

networks:
  movies_network:
